{ pkgs }: [
  pkgs.vim
  pkgs.neovim
  pkgs.tmux
  pkgs.mkalias
  pkgs.git
  pkgs.docker
  (pkgs.google-cloud-sdk.withExtraComponents [
    pkgs.google-cloud-sdk.components.gke-gcloud-auth-plugin
  ])
  pkgs.zsh
  pkgs.pyenv
  pkgs.autojump
  pkgs.kubectl
  pkgs.kubernetes-helm
  pkgs.terraform
  pkgs.httpie
  pkgs.zsh-syntax-highlighting
  pkgs.zsh-history-substring-search
  pkgs.zsh-autosuggestions
  pkgs.gh
  pkgs.zsh-powerlevel10k
  pkgs.openssl
  pkgs.zinit
  pkgs.stow
  pkgs.fzf
  pkgs.zoxide
  pkgs.kubectx
  pkgs.zsh-history-substring-search
  pkgs.kitty
  pkgs.wezterm
  pkgs.direnv
  pkgs.nix-direnv
  pkgs.jq
  pkgs.nodejs_22
  pkgs.python3
  pkgs.mas
  pkgs.helix
  pkgs.helix-gpt
  pkgs.confluent-cli
  pkgs.ripgrep
  pkgs.fd
  pkgs.bat
  pkgs.zellij
  pkgs.colorls
  pkgs.lazygit
  pkgs.mongosh
  pkgs.inetutils
  pkgs.mongodb-tools
  pkgs.iterm2
  pkgs.claude-code
  pkgs.rustc
  pkgs.uv
  pkgs.ollama
  pkgs.k9s
  pkgs.ghostty-bin
  # pkgs.crewai
  pkgs.go
  pkgs.wget
  pkgs.jdk11
  pkgs.luajitPackages.luarocks_bootstrap
  pkgs.lazydocker
  pkgs.bun
  pkgs.github-copilot-cli
  pkgs.gemini-cli
  pkgs.warp-terminal
]
