model_list:
  - model_name: claude-haiku-4.5
    litellm_params:
      model: github_copilot/claude-haiku-4.5
      extra_headers:
        Editor-Version: "vscode/1.95.0"
        Editor-Plugin-Version: "copilot-chat/0.22.0"
  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: github_copilot/claude-haiku-4.5
      extra_headers:
        Editor-Version: "vscode/1.95.0"
        Editor-Plugin-Version: "copilot-chat/0.22.0"
  - model_name: claude-sonnet-4.5
    litellm_params:
      model: github_copilot/claude-sonnet-4.5
      extra_headers:
        Editor-Version: "vscode/1.95.0"
        Editor-Plugin-Version: "copilot-chat/0.22.0"
  

  - model_name: claude-opus-4.5
    litellm_params:
      model: github_copilot/claude-opus-4.5
      extra_headers:
        Editor-Version: "vscode/1.95.0"
        Editor-Plugin-Version: "copilot-chat/0.22.0"

  - model_name: claude-sonnet-4
    litellm_params:
      model: github_copilot/claude-sonnet-4
      extra_headers:
        Editor-Version: "vscode/1.95.0"
        Editor-Plugin-Version: "copilot-chat/0.22.0"

  - model_name: claude-3.5-sonnet
    litellm_params:
      model: github_copilot/claude-3.5-sonnet
      extra_headers:
        Editor-Version: "vscode/1.95.0"
        Editor-Plugin-Version: "copilot-chat/0.22.0"

litellm_settings:
  drop_params: True
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

general_settings:
  master_key: sk-1234
  database_url: "postgresql://litellm:litellm_password@postgres:5432/litellm"
  store_model_in_db: True
  disable_end_user_cost_tracking: True
